version: '3.9'
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build:
      context: ./Frontend
      args:
        REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:80"
    networks:
      - appnet

networks:
  appnet:
